default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
        exclude: '\.pdm-python|resources/.*\.json|.gitignore'
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.0.1
  #   hooks:
  #     - id: mypy
  #       name: Mypy Type Checker
  #       args: ["--explicit-package-bases"]
  #       additional_dependencies: [pydantic==2.9.2]
  #       stages: [pre-commit]

  # there is a conflict between ruff format and isort so lets disable it for now
  # - repo: https://github.com/pycqa/isort
  #   rev: 6.0.0
  #   hooks:
  #     - id: isort
  #       name: isort (python)
