#  ECS / EC2 / Fragate,..

# This will run on each accepted pull request to main repo
name: Deploy to AWS ECS

on:
  pull_request:
    branches: [main]

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "For Auto Deployment"
