# could be pdm publish to pypi/github (if we gonna make it public repo)  or docker publish to ECR
# This publish will be to github repo

name: PDM and Docker Publish

on:
  pull_request:
    branches: [main]

jobs:
  github-publish:
    name: upload release to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4

      - name: Publish package distributions to GitHub Packages
        run: |
          pdm config repository.github.url https://upload.pypi.org/legacy/
          pdm publish --repository github
        env:
        PDM_PUBLISH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  # TODO:: publish to ECR
