name: PDM and Docker Publish

on:
  push:
    branches: [feat/abdel]
  pull_request:
    branches: [main] # TODO:: keep it only main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      DOCKER_IMAGE_NAME: carnival
      ECR_REPOSITORY: carnival
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Root directory as the build context
          load: true
          tags: ${{ needs.build.outputs.DOCKER_IMAGE_NAME }}:latest # Reference the "constant" value here
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: docker run ${{ needs.build.outputs.DOCKER_IMAGE_NAME }}:latest echo "Docker image built successfully"

  publish-docker:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ needs.build.outputs.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
            ${{ env.ECR_REGISTRY }}/${{ needs.build.outputs.ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # TODO:: publish PDM to PyPI or GitHub Packages
